correction table visualization
NowAlexIndustries/moonshine pull request #5
Opened 2024-03-11 15:00 UTC by Dari161

Make a excel sheet, where correction data is visualised with colors.

Also contains some "semi" useless files: a duplicate of everything with dark mode and copyright year auto updater.

2024-03-11 21:03 UTC, Dari161 commented
Nincs jobb csv, amin nem gyakrabban vannak az értékek 1 foknál és 1 százaléknál, meg ami kiterjedtebb?

2024-03-12 07:52 UTC, NowAlexIndustries requested changes
Please rename 'assets' to 'res' to follow development-wide pre-existing standards.

Also in general dont yeet files into root, and next time create clearly-designated folder for files only meant to aid development.

Before merge, resolve duplicate file issues and general structurelessness in folders.

2024-03-12 07:52 UTC, NowAlexIndustries commented on assets/sun.png
This is a placeholder right?

2024-03-12 07:52 UTC, NowAlexIndustries commented on base.css
Use pre-existing folder structure before merge-request as this messes up folder structure on origin as well

2024-03-12 07:52 UTC, NowAlexIndustries commented on index.js
What if we separated dark and light mode css files and than we would only have to change the associated css file in head? Also lets look into cookies and how to check defaults for a fix for the reload issue

2024-03-13 04:53 UTC, Dari161 commented on assets/sun.png
yep

2024-03-21 10:09 UTC, closed without merging